import pandas as pd

# Create a DataFrame from the provided data
data = {
    'Dst Port': [23],
    'Protocol': [6],
    'Timestamp': ['1/3/2018 2:31'],
    'Flow Duration': [118962190],
    'Tot Fwd Pkts': [2],
    'Tot Bwd Pkts': [0],
    'TotLen Fwd Pkts': [0],
    'TotLen Bwd Pkts': [0],
    'Fwd Pkt Len Max': [0],
    'Fwd Pkt Len Min': [0],
    'Fwd Pkt Len Mean': [0],
    'Fwd Pkt Len Std': [0],
    'Bwd Pkt Len Max': [0],
    'Bwd Pkt Len Min': [0],
    'Bwd Pkt Len Mean': [0],
    'Bwd Pkt Len Std': [0],
    'Flow Byts/s': [0.016812064],
    'Flow Pkts/s': [119000000],
    'Flow IAT Mean': [0],
    'Flow IAT Std': [119000000],
    'Flow IAT Max': [119000000],
    'Flow IAT Min': [119000000],
    'Fwd IAT Tot': [119000000],
    'Fwd IAT Mean': [0],
    'Fwd IAT Std': [119000000],
    'Fwd IAT Max': [119000000],
    'Fwd IAT Min': [0],
    'Bwd IAT Tot': [0],
    'Bwd IAT Mean': [0],
    'Bwd IAT Std': [0],
    'Bwd IAT Max': [0],
    'Bwd IAT Min': [0],
    'Fwd PSH Flags': [40],
    'Bwd PSH Flags': [0],
    'Fwd URG Flags': [0],
    'Bwd URG Flags': [0],
    'Fwd Header Len': [0.016812064],
    'Bwd Header Len': [0],
    'Fwd Pkts/s': [0],
    'Bwd Pkts/s': [0],
    'Pkt Len Min': [0],
    'Pkt Len Max': [0],
    'Pkt Len Mean': [0],
    'Pkt Len Std': [0],
    'Pkt Len Var': [0],
    'FIN Flag Cnt': [0],
    'SYN Flag Cnt': [0],
    'RST Flag Cnt': [0],
    'PSH Flag Cnt': [0],
    'ACK Flag Cnt': [0],
    'URG Flag Cnt': [0],
    'CWE Flag Count': [1],
    'ECE Flag Cnt': [0],
    'Down/Up Ratio': [0],
    'Pkt Size Avg': [0],
    'Fwd Seg Size Avg': [0],
    'Bwd Seg Size Avg': [0],
    'Fwd Byts/b Avg': [0],
    'Fwd Pkts/b Avg': [0],
    'Fwd Blk Rate Avg': [0],
    'Bwd Byts/b Avg': [0],
    'Bwd Pkts/b Avg': [0],
    'Bwd Blk Rate Avg': [0],
    'Subflow Fwd Pkts': [0],
    'Subflow Fwd Byts': [0],
    'Subflow Bwd Pkts': [0],
    'Subflow Bwd Byts': [0],
    'Init Fwd Win Byts': [0],
    'Init Bwd Win Byts': [0],
    'Fwd Act Data Pkts': [0],
    'Fwd Seg Size Min': [0],
    'Active Mean': [2],
    'Active Std': [0],
    'Active Max': [0],
    'Active Min': [0],
    'Idle Mean': [0],
    'Idle Std': [0],
    'Idle Max': [0],
    'Idle Min': [0],
    'Label': ['Infilteration']
}

df = pd.DataFrame(data)

# Save the DataFrame to PCAM format
df.to_csv('output.pcam', index=False)
